var primjeri = [
  {
    name:'Domaci 3',
    prefs:[ 'Oblačno', 'Blago', 'Visoka', 'Nema'],
    data:`<table>
    <tr>
    <td>Oblačnost</td> 
    <td>Temperatura</td> 
    <td>Vlažnost</td>  
    <td>Vjetar</td>  
    <td>Igra</td>
    </tr>
    <tr>
    <td>Sunce</td> 
    <td>Vruće</td> 
    <td>Velika</td>  
    <td>Nema</td>  
    <td>Ne</td>
    </tr>
    <tr>
    <td>Sunce</td> 
    <td>Vruće</td> 
    <td>Velika</td>  
    <td>Ima</td> 
    <td>Ne</td>
    </tr>
    <tr>
    <td>Oblačno</td> 
    <td>Vruće</td> 
    <td>Velika</td>  
    <td>Nema</td>  
    <td>Da</td>
    </tr>
    <tr>
    <td>Kiša</td>  
    <td>Blago</td> 
    <td>Velika</td>  
    <td>Nema</td>  
    <td>Da</td>
    </tr>
    <tr>
    <td>Kiša</td>  
    <td>Hladno</td>  
    <td>Normalna</td>  
    <td>Nema</td>  
    <td>Da</td>
    </tr>
    <tr>
    <td>Kiša</td>  
    <td>Hladno</td>  
    <td>Normalna</td>  
    <td>Ima</td> 
    <td>Ne</td>
    </tr>
    <tr>
    <td>Oblačno</td> 
    <td>Hladno</td>  
    <td>Normalna</td>  
    <td>Ima</td> 
    <td>Da</td>
    </tr>
    <tr>
    <td>Sunce</td> 
    <td>Blago</td> 
    <td>Velika</td>  
    <td>Nema</td>  
    <td>Ne</td>
    </tr>
    <tr>
    <td>Sunce</td> 
    <td>Hladno</td>  
    <td>Normalna</td>  
    <td>Nema</td>  
    <td>Da</td>
    </tr>
    <tr>
    <td>Kiša</td>  
    <td>Blago</td> 
    <td>Normalna</td>  
    <td>Nema</td>  
    <td>Da</td>
    </tr>
    <tr>
    <td>Sunce</td> 
    <td>Blago</td> 
    <td>Normalna</td>  
    <td>Ima</td> 
    <td>Da</td>
    </tr>
    <tr>
    <td>Oblačno</td> 
    <td>Blago</td> 
    <td>Velika</td>  
    <td>Ima</td> 
    <td>Da</td>
    </tr>
    <tr>
    <td>Oblačno</td> 
    <td>Vruće</td> 
    <td>Normalna</td>  
    <td>Nema</td>  
    <td>Da</td>
    </tr>
    <tr>
    <td>Kiša</td>  
    <td>Blago</td> 
    <td>Velika</td>  
    <td>Nema</td>  
    <td>Ne</td>
    </tr>
    <tr>
    <td>Oblačno</td> 
    <td>Hladno</td>  
    <td>Normalna</td>  
    <td>Nema</td>  
    <td>Da</td>
    </tr>
    <tr>
    <td>Sunce</td> 
    <td>Vruće</td> 
    <td>Velika</td>  
    <td>Nema</td>  
    <td>Ne</td>
    </tr>
    <tr>
    <td>Sunce</td> 
    <td>Blago</td> 
    <td>Normalna</td>  
    <td>Nema</td>  
    <td>Da</td>
    </tr>
    <tr>
    <td>Kiša</td>  
    <td>Hladno</td>  
    <td>Velika</td>  
    <td>Nema</td>  
    <td>Ne</td>
    </tr>
    <tr>
    <td>Kiša</td>  
    <td>Vruće</td> 
    <td>Velika</td>  
    <td>Ima</td> 
    <td>Ne</td>
    </tr>
    <tr>
    <td>Kiša</td>  
    <td>Blago</td> 
    <td>Velika</td>  
    <td>Ima</td> 
    <td>Ne</td>
    </tr>
    </table>`
  },
  {
    name:'Primjer iz: Klasifikacija-Naivni-Bajes-2015.pdf',
    prefs:[
      'sunny', 'cool', 'high', 'true'
    ],
    data: `<table>
    <tr>
      <td>Outlook</td>
      <td>Temp.</td>
      <td>Humidity</td>
      <td>Windy</td>
      <td>Play</td>
    </tr>
    <tr>
      <td>sunny</td>
      <td>hot</td>
      <td>high</td>
      <td>false</td>
      <td>no</td>
    </tr>
    <tr>
      <td>sunny</td>
      <td>hot</td>
      <td>high</td>
      <td>true</td>
      <td>no</td>
    </tr>
    <tr>
      <td>overcast</td>
      <td>hot</td>
      <td>high</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>rainy</td>
      <td>mild</td>
      <td>high</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>rainy</td>
      <td>cool</td>
      <td>normal</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>rainy</td>
      <td>cool</td>
      <td>normal</td>
      <td>true</td>
      <td>no</td>
    </tr>
    <tr>
      <td>overcast</td>
      <td>cool</td>
      <td>normal</td>
      <td>true</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>sunny</td>
      <td>mild</td>
      <td>high</td>
      <td>false</td>
      <td>no</td>
    </tr>
    <tr>
      <td>sunny</td>
      <td>cool</td>
      <td>normal</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>rainy</td>
      <td>mild</td>
      <td>normal</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>sunny</td>
      <td>mild</td>
      <td>normal</td>
      <td>true</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>overcast</td>
      <td>mild</td>
      <td>high</td>
      <td>true</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>overcast</td>
      <td>hot</td>
      <td>normal</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>rainy</td>
      <td>mild</td>
      <td>high</td>
      <td>true</td>
      <td>no</td>
    </tr>
</table>`
  },
  {
    name:'Youtube primjer: 03.post.01 « Laplace Smoothing « Machine Learning « NUS School of Computing',
    data: `<table>
    <tr>
    <td>Outlook</td> 
    <td>Temperature</td> 
    <td>Humidity</td> 
    <td>Windy</td>  
    <td>Play Golf</td>
    </tr>
    <tr>
    <td>Rainy</td> 
    <td>Hot</td> 
    <td>High</td>  
    <td>False</td> 
    <td>No</td>
    </tr>
    <tr>
    <td>Rainy</td> 
    <td>Hot</td> 
    <td>High</td>  
    <td>True</td>  
    <td>No</td>
    </tr>
    <tr>
    <td>Overcast</td>  
    <td>Hot</td> 
    <td>High</td>  
    <td>False</td> 
    <td>Yes</td>
    </tr>
    <tr>
    <td>Sunny</td> 
    <td>Mild</td>  
    <td>High</td>  
    <td>False</td> 
    <td>Yes</td>
    </tr>
    <tr>
    <td>Sunny</td> 
    <td>Cool</td>  
    <td>Normal</td>  
    <td>False</td> 
    <td>Yes</td>
    </tr>
    <tr>
    <td>Sunny</td> 
    <td>Cool</td>  
    <td>Normal</td>  
    <td>True</td>  
    <td>No</td>
    </tr>
    <tr>
    <td>Overcast</td>  
    <td>Cool</td>  
    <td>Normal</td>  
    <td>True</td>  
    <td>Yes</td>
    </tr>
    <tr>
    <td>Rainy</td> 
    <td>Mild</td>  
    <td>High</td>  
    <td>False</td> 
    <td>No</td>
    </tr>
    <tr>
    <td>Rainy</td> 
    <td>Cool</td>  
    <td>Normal</td>  
    <td>False</td> 
    <td>Yes</td>
    </tr>
    <tr>
    <td>Sunny</td> 
    <td>Mild</td>  
    <td>Normal</td>  
    <td>False</td> 
    <td>Yes</td>
    </tr>
    <tr>
    <td>Rainy</td> 
    <td>Mild</td>  
    <td>Normal</td>  
    <td>True</td>  
    <td>Yes</td>
    </tr>
    <tr>
    <td>Overcast</td>  
    <td>Mild</td>  
    <td>High</td>  
    <td>True</td>  
    <td>Yes</td>
    </tr>
    <tr>
    <td>Overcast</td>  
    <td>Hot</td> 
    <td>Normal</td>  
    <td>False</td> 
    <td>Yes</td>
    </tr>
    <tr>
    <td>Sunny</td> 
    <td>Mild</td>  
    <td>High</td>  
    <td>True</td>  
    <td>No</td>
    </tr>
    </table>`
  },
  {
    name:'Primjer: 2017_Maja/DT_AHP_CSP.pdf',
    data:` <table>
    <tr>
      <td>Temperature</td>
      <td>Outlook</td>
      <td>Humidity</td>
      <td>Windy</td>
      <td>Play Golf?</td>
    </tr>
    <tr>
      <td>hot</td>
      <td>sunny</td>
      <td>high</td>
      <td>false</td>
      <td>no</td>
    </tr>
    <tr>
      <td>hot</td>
      <td>sunny</td>
      <td>high</td>
      <td>true</td>
      <td>no</td>
    </tr>
    <tr>
      <td>hot</td>
      <td>overcast</td>
      <td>high</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>cool</td>
      <td>rain</td>
      <td>normal</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>cool</td>
      <td>overcast</td>
      <td>normal</td>
      <td>true</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>mild</td>
      <td>sunny</td>
      <td>high</td>
      <td>false</td>
      <td>no</td>
    </tr>
    <tr>
      <td>cool</td>
      <td>sunny</td>
      <td>normal</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>mild</td>
      <td>rain</td>
      <td>normal</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>mild</td>
      <td>sunny</td>
      <td>normal</td>
      <td>true</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>mild</td>
      <td>overcast</td>
      <td>high</td>
      <td>true</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>hot</td>
      <td>overcast</td>
      <td>normal</td>
      <td>false</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>mild</td>
      <td>rain</td>
      <td>high</td>
      <td>true</td>
      <td>no</td>
    </tr>
    <tr>
      <td>cool</td>
      <td>rain</td>
      <td>normal</td>
      <td>true</td>
      <td>no</td>
    </tr>
    <tr>
      <td>mild</td>
      <td>rain</td>
      <td>high</td>
      <td>false</td>
      <td>yes</td>
    </tr>
  </table>`
  }
]